# crystalize_project.py
import os

def crystalize():
    base_path = "./app"
    print("🚀 Iniciando Cristalização do Projeto...")

    for root, dirs, files in os.walk(base_path):
        # 1. Garante que toda pasta tenha um __init__.py para ser um pacote Python
        if "__init__.py" not in files:
            with open(os.path.join(root, "__init__.py"), "w") as f:
                f.write("# Auto-generated by Jarvis Nexus\n")
            print(f"  [+] __init__.py criado em: {root}")

        # 2. Verifica se as classes dentro dos arquivos batem com o nome do arquivo
        for file in files:
            if file.endswith(".py") and file != "__init__.py":
                name_no_ext = file[:-3]
                expected_class = "".join(x.capitalize() for x in name_no_ext.split("_"))

                with open(os.path.join(root, file), "r", encoding="utf-8") as f:
                    content = f.read()
                    if f"class {expected_class}" not in content:
                        print(f"  [⚠️] ALERTA: Arquivo '{file}' não parece ter a classe '{expected_class}'.")

    print("✅ Projeto pronto para o Nexus.")

if __name__ == "__main__":
    crystalize()
