import os
import re
import logging
from pathlib import Path

# Configuração de Logging para transparência total na execução
logging.basicConfig(level=logging.INFO, format='[%(levelname)s] %(message)s')
logger = logging.getLogger("Crystallizer")

class ProjectCrystallizer:
    def __init__(self, base_path: str = "./app"):
        self.base_path = Path(base_path)
        self.ignore_files = {
            "__init__.py",
            "nexus.py",
            "nexuscomponent.py",
        }

        # Import padronizado para todos os componentes
        self.component_import = (
            "from app.core.nexuscomponent import NexusComponent\n\n"
        )

    def _to_pascal_case(self, name: str) -> str:
        """Converte snake_case para PascalCase (ex: monitor_cpu -> MonitorCpu)"""
        return "".join(word.capitalize() for word in name.split("_"))

    def crystallize(self):
        logger.info("💎 [CRISTALIZADOR] Iniciando Operação de Auto-Cura...")

        if not self.base_path.exists():
            logger.error(f"Caminho base {self.base_path} não encontrado.")
            return

        for root, _, files in os.walk(self.base_path):
            root_path = Path(root)

            # Garante que todo diretório seja um pacote Python válido
            init_file = root_path / "__init__.py"
            if not init_file.exists():
                init_file.write_text("# Auto-generated by JARVIS\n", encoding="utf-8")

            for file in files:
                if not file.endswith(".py") or file in self.ignore_files:
                    continue

                self._fix_file(root_path / file)

        logger.info("✅ [CRISTALIZADOR] Projeto Cristalizado e Estabilizado.")

    def _fix_file(self, file_path: Path):
        file_id = file_path.stem
        expected_class = self._to_pascal_case(file_id)

        try:
            content = file_path.read_text(encoding="utf-8")
        except Exception as e:
            logger.error(f"Erro ao ler {file_path}: {e}")
            return

        # Limpeza: Remove atribuições corrompidas onde a classe tenta ser igual a 'class'
        content = re.sub(
            rf"^{expected_class}\s*=\s*class\b.*$",
            "",
            content,
            flags=re.MULTILINE,
        )

        # Identifica classes existentes no arquivo
        found_classes = re.findall(
            r"^class\s+([A-Za-z0-9_]+)",
            content,
            flags=re.MULTILINE,
        )

        # CENÁRIO 1: A classe esperada já existe
        if expected_class in found_classes:
            self._ensure_contract(file_path, content, expected_class)
            return

        # CENÁRIO 2: Existe uma classe, mas com nome diferente do arquivo (Cria Alias)
        if found_classes:
            primary_class = found_classes[0]
            alias_line = f"{expected_class} = {primary_class}"

            if alias_line not in content:
                logger.info(f"  [🔗] Criando Alias: {expected_class} -> {primary_class}")
                content = content.rstrip() + f"\n\n# Nexus Compatibility\n{alias_line}\n"

            self._ensure_contract(file_path, content, primary_class)
            return

        # CENÁRIO 3: Código solto (Script). Envelopa em uma classe NexusComponent.
        if content.strip():
            logger.info(f"  [📦] Envelopando script: {file_path.name}")

            # Melhoria: Indentação segura preservando linhas vazias
            indented = "\n".join(
                f"        {line}" if line.strip() else line
                for line in content.splitlines()
            )

            new_content = (
                f"{self.component_import}"
                f"class {expected_class}(NexusComponent):\n"
                f"    def execute(self, context: dict):\n"
                f"        \"\"\"Execução automatizada do script original\"\"\"\n"
                f"{indented}\n"
            )

            file_path.write_text(new_content, encoding="utf-8")

    def _ensure_contract(self, file_path: Path, content: str, class_name: str):
        """Garante que a classe herda de NexusComponent e possui o método execute."""
        updated = False

        # Injeta o import se necessário
        if "NexusComponent" not in content:
            content = self.component_import + content
            updated = True

        # Regex para encontrar a definição da classe e capturar herança
        class_pattern = rf"class\s+({class_name})\s*(\(([^)]*)\))?:"
        match = re.search(class_pattern, content)

        if not match:
            return

        full_class_def = match.group(0)
        inheritance = match.group(3) if match.group(3) else ""

        # Garante herança de NexusComponent
        if "NexusComponent" not in inheritance:
            new_inheritance = f"({inheritance}, NexusComponent)" if inheritance else "(NexusComponent)"
            new_class_def = f"class {class_name}{new_inheritance}:"
            content = content.replace(full_class_def, new_class_def)
            updated = True

        # Garante existência do método execute
        # Procuramos o método apenas dentro do escopo da classe para evitar falsos positivos
        class_block_start = content.find(new_class_def if updated else full_class_def)
        if "def execute(" not in content[class_block_start:]:
            logger.info(f"  [➕] Injetando execute() em {class_name}")
            insertion_point = content.find(":", class_block_start) + 1
            insert = (
                f"\n    def execute(self, context: dict):\n"
                f"        # TODO: Implementar lógica do componente\n"
                f"        raise NotImplementedError(\"Método execute não implementado em {class_name}\")\n"
            )
            content = content[:insertion_point] + insert + content[insertion_point:]
            updated = True

        if updated:
            file_path.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    # Executa a cristalização no diretório padrão
    ProjectCrystallizer().crystallize()
