#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
PR Manager - Git branch management, commits, pull requests, and issue lifecycle.

Provides standalone functions for all Git and GitHub CLI operations required
by the self-healing system: branch creation, committing, pushing, opening
pull requests, closing issues, and the end-to-end attempt_repair orchestrator
that ties together issue parsing, fix generation, validation, and Git ops.
"""

import logging
import subprocess
from pathlib import Path
from typing import Any, Dict, Optional

from scripts import fix_applier, issue_parser

logger = logging.getLogger(__name__)


def create_branch(issue_id: str, repo_path: Path) -> bool:
    """Create and checkout branch fix/issue-{issue_id}, or check out if it already exists."""
    branch_name = f"fix/issue-{issue_id}"
    try:
        result = subprocess.run(
            ["git", "checkout", "-b", branch_name],
            cwd=repo_path, capture_output=True, text=True, timeout=30,
        )
        if result.returncode == 0:
            logger.info(f"✓ Created branch: {branch_name}")
            return True
        # Branch might already exist — try checking it out
        result = subprocess.run(
            ["git", "checkout", branch_name],
            cwd=repo_path, capture_output=True, text=True, timeout=30,
        )
        if result.returncode == 0:
            logger.info(f"✓ Checked out existing branch: {branch_name}")
            return True
        logger.error(f"Failed to create/checkout branch: {result.stderr}")
        return False
    except Exception as e:
        logger.error(f"Error creating branch: {e}")
        return False


def commit_changes(file_path: str, issue_id: str, repo_path: Path) -> bool:
    """Stage file_path and create an auto-fix commit referencing issue_id."""
    try:
        subprocess.run(
            ["git", "add", file_path],
            cwd=repo_path, capture_output=True, text=True, timeout=30,
        )
        commit_message = (
            f"Auto-fix: Resolve issue #{issue_id}\n\n"
            "[Auto-generated by Jarvis Self-Healing System]"
        )
        result = subprocess.run(
            ["git", "commit", "-m", commit_message],
            cwd=repo_path, capture_output=True, text=True, timeout=30,
        )
        if result.returncode == 0:
            logger.info(f"✓ Committed changes: {commit_message.splitlines()[0]}")
            return True
        logger.error(f"Failed to commit: {result.stderr}")
        return False
    except Exception as e:
        logger.error(f"Error committing changes: {e}")
        return False


def push_branch(issue_id: str, repo_path: Path) -> bool:
    """Push the fix/issue-{issue_id} branch to origin with upstream tracking."""
    branch_name = f"fix/issue-{issue_id}"
    try:
        result = subprocess.run(
            ["git", "push", "-u", "origin", branch_name],
            cwd=repo_path, capture_output=True, text=True, timeout=60,
        )
        if result.returncode == 0:
            logger.info(f"✓ Pushed branch {branch_name} to remote")
            return True
        logger.error(f"Failed to push branch: {result.stderr}")
        return False
    except Exception as e:
        logger.error(f"Error pushing branch: {e}")
        return False


def create_pull_request(
    issue_id: str, error_message: str, file_path: str, repo_path: Path
) -> bool:
    """
    Create a pull request using GitHub CLI.

    Args:
        issue_id: The issue ID.
        error_message: The original error message (used in the PR body).
        file_path: Path to the fixed file.
        repo_path: Root path of the repository.

    Returns:
        True if successful, False otherwise.
    """
    try:
        title = f"Auto-fix: Resolve issue #{issue_id}"
        error_preview = fix_applier.truncate_log(error_message, 500)
        body = (
            "## 🤖 Auto-Generated Fix\n\n"
            "This PR was automatically generated by the Jarvis Self-Healing System "
            "using GitHub Copilot CLI.\n\n"
            f"### Issue\nFixes #{issue_id}\n\n"
            f"### Error\n```\n{error_preview}\n```\n\n"
            f"### Changes\n- Fixed error in `{file_path}`\n"
            "- Applied AI-generated correction using GitHub Copilot CLI (`gh copilot`)\n\n"
            "### Verification\n"
            "⚠️ **Important:** Please review the changes carefully before merging.\n"
            "This PR was automatically generated and should be tested before deployment.\n\n"
            "---\n_Generated by Jarvis Self-Healing Orchestrator with GitHub Copilot_\n"
        )
        result = subprocess.run(
            ["gh", "pr", "create", "--title", title, "--body", body],
            cwd=repo_path, capture_output=True, text=True, timeout=60,
        )
        if result.returncode == 0:
            logger.info(f"✓ Created pull request: {result.stdout.strip()}")
            return True
        logger.error(f"Failed to create PR: {result.stderr}")
        return False
    except Exception as e:
        logger.error(f"Error creating pull request: {e}")
        return False


def close_issue(issue_id: str, repo_path: Path) -> bool:
    """
    Close the original issue using GitHub CLI.

    Args:
        issue_id: The issue ID to close.
        repo_path: Root path of the repository.

    Returns:
        True if successful, False otherwise.
    """
    try:
        comment = 'Correção aplicada automaticamente via Jarvis Self-Healing. Pull Request criado.'
        result = subprocess.run(
            ["gh", "issue", "close", issue_id, "--comment", comment],
            cwd=repo_path, capture_output=True, text=True, timeout=60,
        )
        if result.returncode == 0:
            logger.info(f"✓ Closed issue #{issue_id}")
            return True
        logger.error(f"Failed to close issue: {result.stderr}")
        return False
    except Exception as e:
        logger.error(f"Error closing issue: {e}")
        return False


def attempt_repair(issue_body: str, issue_id: str, repo_path: Path) -> Dict[str, Any]:
    """
    Orchestrate a single repair attempt (1 file, 1 fix at a time).

    Detects the target file, requests a fix from GitHub Copilot, validates it
    with pytest, applies it, and creates a Git branch / PR / closes the issue.

    Args:
        issue_body: The issue description or error text.
        issue_id: The issue ID.
        repo_path: Root path of the repository.

    Returns:
        Dictionary with keys:
            - success (bool): Whether the repair succeeded.
            - file (str): The file that was targeted.
            - description (str): Human-readable description of the outcome.
    """
    is_doc = issue_parser.is_documentation_request(issue_body)
    is_feature = issue_parser.is_feature_request(issue_body)
    fix_type = "documentation update" if is_doc else ("feature implementation" if is_feature else "bug fix")

    if is_doc:
        logger.info("\n📚 Detected documentation update request")
    elif is_feature:
        logger.info("\n✨ Detected feature request")
    else:
        logger.info("\n🐛 Detected bug fix request")

    # Locate target file
    file_path: Optional[str] = issue_parser.extract_file_from_error(issue_body)
    if not file_path:
        logger.info("No file path found in traceback, searching for common files...")
        file_path = issue_parser.extract_common_filename(issue_body, repo_path)
    if not file_path:
        logger.info("No common files found, searching by keywords...")
        file_path = issue_parser.suggest_file_by_keywords(issue_body, repo_path)
    if not file_path:
        issue_lower = issue_body.lower()
        meta_keywords = ['self-healing', 'self healing', 'auto-fixer', 'auto fixer', 'github actions', 'workflow', 'jarvis']
        if any(kw in issue_lower for kw in meta_keywords):
            logger.info("Detected meta-issue about self-healing system")
            if 'github actions' in issue_lower or 'workflow' in issue_lower:
                file_path = '.github/workflows/jarvis_code_fixer.yml'
            elif 'state machine' in issue_lower or 'state-machine' in issue_lower:
                file_path = 'scripts/state_machine.py'
            else:
                file_path = 'scripts/auto_fixer_logic.py'
            logger.info(f"Suggesting: {file_path}")

    if not file_path:
        logger.error("Could not identify target file")
        return {'success': False, 'file': 'Unknown', 'description': f'Tentativa de {fix_type} - arquivo não identificado'}

    logger.info(f"\n🎯 Target file: {file_path}")

    current_code = fix_applier.read_file_content(file_path, repo_path)
    if not current_code:
        logger.error(f"Could not read file: {file_path}")
        return {'success': False, 'file': file_path, 'description': f'Tentativa de {fix_type} - falha ao ler arquivo'}

    logger.info("\n🤖 Requesting fix from GitHub Copilot...")
    fixed_code = fix_applier.get_fixed_code_with_copilot(issue_body, current_code, file_path, repo_path, is_doc, is_feature)
    if not fixed_code:
        logger.error("Failed to get fix from GitHub Copilot")
        return {'success': False, 'file': file_path, 'description': f'Tentativa de {fix_type} - GitHub Copilot não gerou correção'}

    # Validate: syntax check + pytest on a temp file before touching real file
    file_suffix = Path(file_path).suffix or ".py"
    temp_path = repo_path / f"_temp_test_{issue_id}{file_suffix}"
    try:
        temp_path.write_text(fixed_code, encoding="utf-8")
        if file_suffix == ".py":
            try:
                compile(fixed_code, str(temp_path), "exec")
            except SyntaxError as syntax_err:
                logger.error("❌ Correção rejeitada: erro de sintaxe Python: %s", syntax_err)
                return {'success': False, 'file': file_path, 'description': 'Correção rejeitada pelos testes.'}

        logger.info("\n🧪 Validando correção com pytest antes de aplicar...")
        pytest_result = subprocess.run(
            ["pytest", "--tb=short", "-q", "tests/"],
            cwd=repo_path, capture_output=True, text=True, timeout=120,
        )
        if pytest_result.returncode != 0:
            logger.error("❌ Pytest falhou — correção não aplicada.\nstdout: %s\nstderr: %s",
                         pytest_result.stdout[-2000:], pytest_result.stderr[-500:])
            return {'success': False, 'file': file_path, 'description': 'Correção rejeitada pelos testes.'}
        logger.info("✅ Validação pytest passou — aplicando correção.")
    except subprocess.TimeoutExpired:
        logger.error("❌ Pytest excedeu timeout (120s) — correção não aplicada.")
        return {'success': False, 'file': file_path, 'description': 'Correção rejeitada pelos testes.'}
    finally:
        if temp_path.exists():
            temp_path.unlink()

    # Apply fix and create Git artifacts
    logger.info(f"\n📝 Applying changes to {file_path}...")
    if not fix_applier.apply_fix(file_path, fixed_code, repo_path):
        return {'success': False, 'file': file_path, 'description': f'Tentativa de {fix_type} - falha ao aplicar correção'}

    logger.info("✅ Fix validated and applied!")
    if not create_branch(issue_id, repo_path):
        logger.warning("Failed to create branch - reverting changes")
        subprocess.run(["git", "checkout", file_path], cwd=repo_path)
        return {'success': False, 'file': file_path, 'description': f'{fix_type.capitalize()} aplicada, pytest passou, mas falha ao criar branch - alterações revertidas'}

    if not commit_changes(file_path, issue_id, repo_path):
        logger.warning("Failed to commit changes - reverting")
        subprocess.run(["git", "checkout", file_path], cwd=repo_path)
        subprocess.run(["git", "checkout", "-"], cwd=repo_path)
        return {'success': False, 'file': file_path, 'description': f'{fix_type.capitalize()} aplicada, pytest passou, mas falha ao fazer commit - alterações revertidas'}

    if not push_branch(issue_id, repo_path):
        logger.warning("Failed to push branch - reverting")
        subprocess.run(["git", "reset", "--hard", "HEAD~1"], cwd=repo_path)
        subprocess.run(["git", "checkout", "-"], cwd=repo_path)
        return {'success': False, 'file': file_path, 'description': f'{fix_type.capitalize()} aplicada, pytest passou, mas falha ao fazer push - alterações revertidas'}

    if not create_pull_request(issue_id, issue_body, file_path, repo_path):
        logger.warning("Failed to create PR")
    if not close_issue(issue_id, repo_path):
        logger.warning("Failed to close issue")

    return {'success': True, 'file': file_path, 'description': f'{fix_type.capitalize()} aplicada com sucesso - pytest passou'}
